version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=productDb
    ports:
      - '54322:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local